export const BRIEF_STAGE = Object.freeze({
  ELIGIBILITY_CHECK: 'BRIEF_ELIGIBILITY_CHECK',
  CORE_QUESTION_RESOLUTION: 'BRIEF_CORE_QUESTION_RESOLUTION',
  KEY_CLAIM_ELIGIBILITY: 'BRIEF_KEY_CLAIM_ELIGIBILITY',
  GENERATION: 'BRIEF_GENERATION',
  VALIDATION: 'BRIEF_VALIDATION',
  PERSISTED: 'BRIEF_PERSISTED',
  LIFECYCLE_TRANSITION: 'BRIEF_LIFECYCLE_TRANSITION'
});