export const RESEARCH_STAGE = Object.freeze({
  RESEARCH_PROJECT_CREATED: 'RESEARCH_PROJECT_CREATED',
  SOURCE_DISCOVERY: 'SOURCE_DISCOVERY',
  SOURCE_ACQUISITION: 'SOURCE_ACQUISITION',
  SOURCE_CLASSIFICATION: 'SOURCE_CLASSIFICATION',
  CLAIM_EXTRACTION: 'CLAIM_EXTRACTION',
  LOAD_BEARING_CLASSIFICATION: 'LOAD_BEARING_CLASSIFICATION',
  CLAIM_TYPE_RECLASSIFICATION: 'CLAIM_TYPE_RECLASSIFICATION',
  EVIDENCE_GRADING: 'EVIDENCE_GRADING',
  CONTRADICTION_CHECK: 'CONTRADICTION_CHECK',
  COMPLETENESS_CHECK: 'COMPLETENESS_CHECK'
});

export const RESEARCH_PROJECT_STATUS = Object.freeze({
  RESEARCHING: 'RESEARCHING',
  RESEARCH_COMPLETE: 'RESEARCH_COMPLETE',
  INSUFFICIENT_EVIDENCE: 'INSUFFICIENT_EVIDENCE',
  FAILED: 'FAILED'
});

export const CLAIM_TYPE = Object.freeze({
  FACT: 'FACT',
  INFERENCE: 'INFERENCE',
  OPINION: 'OPINION'
});

export const EVIDENCE_STATUS = Object.freeze({
  VERIFIED: 'VERIFIED',
  PARTIALLY_SUPPORTED: 'PARTIALLY_SUPPORTED',
  UNSUPPORTED: 'UNSUPPORTED',
  CONTESTED: 'CONTESTED'
});

export const SOURCE_ROLE = Object.freeze({
  PRIMARY_AUTHORITATIVE: 'primary_authoritative',
  INDEPENDENT_REPORTING: 'independent_reporting',
  SYNDICATED: 'syndicated'
});

export const SOURCE_QUALITY = Object.freeze({
  HIGH: 'HIGH',
  MEDIUM: 'MEDIUM',
  LOW: 'LOW',
  UNUSABLE: 'UNUSABLE'
});

export const RETRIEVAL_STATUS = Object.freeze({
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  CONTENT_UNPARSEABLE: 'CONTENT_UNPARSEABLE'
});

export const CORE_QUESTION_TYPE = Object.freeze({
  FACTUAL: 'FACTUAL',
  SENTIMENT: 'SENTIMENT',
  MIXED: 'MIXED'
});