export const SCRIPT_STAGE = Object.freeze({
  ELIGIBILITY_CHECK: 'SCRIPT_ELIGIBILITY_CHECK',
  GENERATION: 'SCRIPT_GENERATION',
  VALIDATION: 'SCRIPT_VALIDATION',
  PERSISTED: 'SCRIPT_PERSISTED',
  LIFECYCLE_TRANSITION: 'SCRIPT_LIFECYCLE_TRANSITION'
});
