export const STAGE = Object.freeze({
  EVENT_DEDUP: 'EVENT_DEDUP',
  HARD_ELIGIBILITY: 'HARD_ELIGIBILITY',
  PROPOSITION_GENERATION: 'PROPOSITION_GENERATION',
  PROPOSITION_VALIDATION: 'PROPOSITION_VALIDATION',
  VALUE_SCORE: 'VALUE_SCORE',
  RISK_GATE: 'RISK_GATE',
  DIVERSITY_SELECTION: 'DIVERSITY_SELECTION'
});

export const REJECTION_REASON = Object.freeze({
  // Hard Eligibility stage
  INELIGIBLE_LANGUAGE: 'INELIGIBLE_LANGUAGE',
  INELIGIBLE_EMPTY_CONTENT: 'INELIGIBLE_EMPTY_CONTENT',
  INELIGIBLE_ALREADY_PRODUCED: 'INELIGIBLE_ALREADY_PRODUCED',
  INELIGIBLE_MALFORMED: 'INELIGIBLE_MALFORMED',
  DUPLICATE: 'DUPLICATE',
  EXPIRED: 'EXPIRED',
  // Proposition Validation stage
  INELIGIBLE_NO_VIABLE_PROPOSITION: 'INELIGIBLE_NO_VIABLE_PROPOSITION',
  // Value/Risk/Diversity stage
  LOW_DEMAND: 'LOW_DEMAND',
  LOW_NOVELTY: 'LOW_NOVELTY',
  HIGH_COMPETITION: 'HIGH_COMPETITION',
  INSUFFICIENT_EVIDENCE: 'INSUFFICIENT_EVIDENCE',
  HIGH_PRODUCTION_DIFFICULTY: 'HIGH_PRODUCTION_DIFFICULTY',
  LOW_MONETIZATION: 'LOW_MONETIZATION',
  HIGH_POLICY_RISK: 'HIGH_POLICY_RISK',
  HIGH_COPYRIGHT_RISK: 'HIGH_COPYRIGHT_RISK',
  HIGH_REPETITION_RISK: 'HIGH_REPETITION_RISK'
});
