export const STAGE = Object.freeze({
  EVENT_DEDUP: 'EVENT_DEDUP',
  HARD_ELIGIBILITY: 'HARD_ELIGIBILITY',
  PROPOSITION_GENERATION: 'PROPOSITION_GENERATION',
  PROPOSITION_VALIDATION: 'PROPOSITION_VALIDATION',
  FEATURE_COMPUTATION: 'FEATURE_COMPUTATION',
  VALUE_SCORE: 'VALUE_SCORE',
  RISK_GATE: 'RISK_GATE',
  DIVERSITY_SELECTION: 'DIVERSITY_SELECTION'
});

export const REJECTION_REASON = Object.freeze({
  // Hard Eligibility stage
  INELIGIBLE_LANGUAGE: 'INELIGIBLE_LANGUAGE',
  INELIGIBLE_EMPTY_CONTENT: 'INELIGIBLE_EMPTY_CONTENT',
  INELIGIBLE_ALREADY_PRODUCED: 'INELIGIBLE_ALREADY_PRODUCED',
  INELIGIBLE_MALFORMED: 'INELIGIBLE_MALFORMED',
  DUPLICATE: 'DUPLICATE',
  EXPIRED: 'EXPIRED',
  // Proposition Validation stage
  INELIGIBLE_NO_VIABLE_PROPOSITION: 'INELIGIBLE_NO_VIABLE_PROPOSITION',
  // Feature Computation stage
  INELIGIBLE_FEATURE_COMPUTATION_FAILED: 'INELIGIBLE_FEATURE_COMPUTATION_FAILED',
  // Value/Risk/Diversity stage
  LOW_DEMAND: 'LOW_DEMAND',
  LOW_NOVELTY: 'LOW_NOVELTY',
  HIGH_COMPETITION: 'HIGH_COMPETITION',
  INSUFFICIENT_EVIDENCE: 'INSUFFICIENT_EVIDENCE',
  HIGH_PRODUCTION_DIFFICULTY: 'HIGH_PRODUCTION_DIFFICULTY',
  LOW_MONETIZATION: 'LOW_MONETIZATION',
  HIGH_POLICY_RISK: 'HIGH_POLICY_RISK',
  HIGH_COPYRIGHT_RISK: 'HIGH_COPYRIGHT_RISK',
  HIGH_REPETITION_RISK: 'HIGH_REPETITION_RISK'
});

// ADR-0038: Discovery Workload Bounds and Fairness Controls (governance-only
// decision; these are the frozen values/codes it authorizes).
export const RSS_ADMISSION = Object.freeze({
  PER_FEED_CAP: 50,
  GLOBAL_CAP: 50
});

// Both tied to the global RSS admission cap via 50 * 49 / 2 = 1,225
// (maximum pairwise comparisons across a 50-item admitted set). If
// RSS_ADMISSION.GLOBAL_CAP ever changes, this basis must be reconsidered --
// ADR-0038 does not pre-authorize any such recalculation.
export const DEDUP_WORKLOAD = Object.freeze({
  L2_COMPARISON_CAP: 1225,
  L3_SEMANTIC_CALL_CAP: 1225
});

// The four, and only four, machine-readable ceiling reason codes ADR-0038
// authorizes. No additional ceiling reason codes may be introduced without
// a separate Owner decision.
export const CEILING_REASON = Object.freeze({
  RSS_PER_FEED_CAP_REACHED: 'RSS_PER_FEED_CAP_REACHED',
  RSS_GLOBAL_CAP_REACHED: 'RSS_GLOBAL_CAP_REACHED',
  DISCOVERY_L2_COMPARISON_CAP_REACHED: 'DISCOVERY_L2_COMPARISON_CAP_REACHED',
  DISCOVERY_L3_SEMANTIC_CALL_CAP_REACHED: 'DISCOVERY_L3_SEMANTIC_CALL_CAP_REACHED'
});
